name: Deploy vite react application to gh pages

on:
  push:
    branches: ["master"]

  # Allow manual deployment
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one instance to deploy at the time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Setup environment
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # build application
      - run: yarn --frozen-lockfile
      - run: yarn build

      # deploy to gh pages
      - name: Setup gh pages
        uses: actions/configure-pages@v2
      - name: Upload react application
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v1
